name: .NET
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Pack NuGet package 2
      run: dotnet pack Shlongo/Shlongo2.csproj --no-build --configuration Release -o ./artifacts

    - name: Pack NuGet package 3
      run: dotnet pack Shlongo/Shlongo3.csproj --no-build --configuration Release -o ./artifacts

    - name: Publish NuGet package
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
